//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseOfUltron_29Feb2016.Resources.Question {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Breach2Question {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Breach2Question() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiseOfUltron_29Feb2016.Resources.Question.Breach2Question", typeof(Breach2Question).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be output if you will compile and 
        ///execute the following c code?
        ///#include &lt;stdio.h&gt;
        /// 
        ///int main()
        ///{
        ///  int a[] = {1, 2, 3, 4, 5, 6};
        ///  int *ptr = (int*)(&amp;&amp;a+1);
        ///  printf(&quot;%d &quot;, *(ptr-1) );
        ///  getchar();
        ///  return 0;
        ///}.
        /// </summary>
        internal static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) 1.
        /// </summary>
        internal static string q1Option1 {
            get {
                return ResourceManager.GetString("q1Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0) 6.
        /// </summary>
        internal static string q1Option2 {
            get {
                return ResourceManager.GetString("q1Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Compile time error.
        /// </summary>
        internal static string q1Option3 {
            get {
                return ResourceManager.GetString("q1Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6) Undefined Behaviour.
        /// </summary>
        internal static string q1Option4 {
            get {
                return ResourceManager.GetString("q1Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be output if you will compile 
        ///and execute the following c code?
        ///int main()
        ///{
        ///  int x, y = 5, z = 5;
        ///  x = y==z;
        ///  printf(&quot;%d&quot;, x);
        ///  return 0;
        ///}.
        /// </summary>
        internal static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) 0.
        /// </summary>
        internal static string q2Option1 {
            get {
                return ResourceManager.GetString("q2Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0) 1.
        /// </summary>
        internal static string q2Option2 {
            get {
                return ResourceManager.GetString("q2Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) 5.
        /// </summary>
        internal static string q2Option3 {
            get {
                return ResourceManager.GetString("q2Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7) garbage.
        /// </summary>
        internal static string q2Option4 {
            get {
                return ResourceManager.GetString("q2Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void fun(int *p)
        ///{
        ///  static int q = 10;
        ///  p = &amp;&amp;q;
        ///}    
        /// 
        ///int main()
        ///{
        ///  int r = 20;
        ///  int *p = &amp;&amp;r;  
        ///  fun(p);
        ///  printf(&quot;%d&quot;, *p);
        ///  getchar();
        ///  return 0;
        ///}.
        /// </summary>
        internal static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) 10.
        /// </summary>
        internal static string q3Option1 {
            get {
                return ResourceManager.GetString("q3Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9) Runtime error.
        /// </summary>
        internal static string q3Option2 {
            get {
                return ResourceManager.GetString("q3Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) None of these.
        /// </summary>
        internal static string q3Option3 {
            get {
                return ResourceManager.GetString("q3Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) 20.
        /// </summary>
        internal static string q3Option4 {
            get {
                return ResourceManager.GetString("q3Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be output if you will compile 
        ///and execute the following c code?
        ///int main()
        ///{
        ///    char arr[] = {1, 2, 3};
        ///    char *p = arr;
        ///    if(&amp;&amp;p == &amp;&amp;arr)
        ///     printf(&quot;Same&quot;);
        ///    else
        ///     printf(&quot;Not same&quot;);
        ///    getchar();
        ///}.
        /// </summary>
        internal static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8) same.
        /// </summary>
        internal static string q4Option1 {
            get {
                return ResourceManager.GetString("q4Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7) not same.
        /// </summary>
        internal static string q4Option2 {
            get {
                return ResourceManager.GetString("q4Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) Runtime error.
        /// </summary>
        internal static string q4Option3 {
            get {
                return ResourceManager.GetString("q4Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Compilation error.
        /// </summary>
        internal static string q4Option4 {
            get {
                return ResourceManager.GetString("q4Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate the value of series 1^2 + 2^2 + …. + n^2
        ///where N is key generated. .
        /// </summary>
        internal static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6930.
        /// </summary>
        internal static string q5Answer {
            get {
                return ResourceManager.GetString("q5Answer", resourceCulture);
            }
        }
    }
}
