//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseOfUltron_29Feb2016.Resources.Question {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Breach1Question {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Breach1Question() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiseOfUltron_29Feb2016.Resources.Question.Breach1Question", typeof(Breach1Question).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be output if you will compile and
        /// execute the following C code?
        ///#include&lt;stdio.h&gt;
        ///#include&lt;conio.h&gt;
        ///void main(){
        ///    int i;
        ///    i=1,2,3,4;
        ///    printf(&quot;%d&quot;,i);  }.
        /// </summary>
        internal static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string q1Answer {
            get {
                return ResourceManager.GetString("q1Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) 1.
        /// </summary>
        internal static string q1Option1 {
            get {
                return ResourceManager.GetString("q1Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8) 4.
        /// </summary>
        internal static string q1Option2 {
            get {
                return ResourceManager.GetString("q1Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0) garbage.
        /// </summary>
        internal static string q1Option3 {
            get {
                return ResourceManager.GetString("q1Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) error.
        /// </summary>
        internal static string q1Option4 {
            get {
                return ResourceManager.GetString("q1Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is the output of the following code?
        ///main()
        ///{    int u1=10, u2=5;
        ///u2=printf(&quot;%d%d&quot;,u1,u2);
        ///printf(&quot;%d%d,u1,u2);
        ///}.
        /// </summary>
        internal static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string q2Answer {
            get {
                return ResourceManager.GetString("q2Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) error.
        /// </summary>
        internal static string q2Option1 {
            get {
                return ResourceManager.GetString("q2Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) 10 5 10 2.
        /// </summary>
        internal static string q2Option2 {
            get {
                return ResourceManager.GetString("q2Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) 10 5 10 5.
        /// </summary>
        internal static string q2Option3 {
            get {
                return ResourceManager.GetString("q2Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8) 5 10 10 5.
        /// </summary>
        internal static string q2Option4 {
            get {
                return ResourceManager.GetString("q2Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be output if you will compile and 
        ///execute the following c code?
        ///void main()
        ///{   int i=65; char c=&apos;A&apos;;
        ///if(i==c)
        ///printf(&quot;Exec&quot;);
        ///else
        ///printf(&quot;Something&quot;);
        ///}.
        /// </summary>
        internal static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string q3Answer {
            get {
                return ResourceManager.GetString("q3Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Something.
        /// </summary>
        internal static string q3Option1 {
            get {
                return ResourceManager.GetString("q3Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) Runtime error.
        /// </summary>
        internal static string q3Option2 {
            get {
                return ResourceManager.GetString("q3Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7) Exec.
        /// </summary>
        internal static string q3Option3 {
            get {
                return ResourceManager.GetString("q3Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0) Compilation error.
        /// </summary>
        internal static string q3Option4 {
            get {
                return ResourceManager.GetString("q3Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will be output if you will compile and 
        ///execute the following c code?(give the input
        ///are 10 &amp;&amp; 12 respectively)
        ///  #include &lt;stdio.h&gt;
        ///int main()
        ///{
        ///int akd,aks;
        ///akd=scanf(&quot;%d%d&quot;,&amp;akd,&amp;aks);
        ///printf(&quot;%d%d&quot;,aks,akd);
        ///}
        ///}.
        /// </summary>
        internal static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string q4Answer {
            get {
                return ResourceManager.GetString("q4Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0) 10 12.
        /// </summary>
        internal static string q4Option1 {
            get {
                return ResourceManager.GetString("q4Option1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4) 2 10.
        /// </summary>
        internal static string q4Option2 {
            get {
                return ResourceManager.GetString("q4Option2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5) 12 2.
        /// </summary>
        internal static string q4Option3 {
            get {
                return ResourceManager.GetString("q4Option3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8) Compilation Error.
        /// </summary>
        internal static string q4Option4 {
            get {
                return ResourceManager.GetString("q4Option4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAP to generate all armstrong values between 0 &amp;&amp; N,
        ///where N is the key.
        ///Enter the total no of armstrong Numbers to complete the
        ///breach..
        /// </summary>
        internal static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string q5Answer {
            get {
                return ResourceManager.GetString("q5Answer", resourceCulture);
            }
        }
    }
}
