//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseOfUltron_29Feb2016.Resources.Question {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Breach3Question {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Breach3Question() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiseOfUltron_29Feb2016.Resources.Question.Breach3Question", typeof(Breach3Question).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string a1 {
            get {
                return ResourceManager.GetString("a1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string a10 {
            get {
                return ResourceManager.GetString("a10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string a2 {
            get {
                return ResourceManager.GetString("a2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string a3 {
            get {
                return ResourceManager.GetString("a3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string a4 {
            get {
                return ResourceManager.GetString("a4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string a5 {
            get {
                return ResourceManager.GetString("a5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string a6 {
            get {
                return ResourceManager.GetString("a6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string a7 {
            get {
                return ResourceManager.GetString("a7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string a8 {
            get {
                return ResourceManager.GetString("a8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string a9 {
            get {
                return ResourceManager.GetString("a9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pugilist is a?
        ///a)Weightlifter	               
        ///b)Cricketer                               
        ///c)Swimmer	                        
        ///d)Boxer.
        /// </summary>
        internal static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michael Phelps, who won the highest 
        ///number of gold medals in Olympic Games 
        ///in 2008 and 2012, broke the record of?
        ///a)Rebecca Adlington        
        ///b)Williamson                      
        ///c)Grant Hackett	          
        ///d)Mark Spitz.
        /// </summary>
        internal static string q10 {
            get {
                return ResourceManager.GetString("q10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of medals won by Indian in
        /// the 2010 Commonwealth Games?
        ///a)98	                              
        ///b)101                                          
        ///c)107	                            
        ///d)96.
        /// </summary>
        internal static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who among the following cricketers 
        ///has been declared the &quot;Cricketer of 
        ///the Twentieth Century&quot; by the ICC?
        ///a)Shane Warne            	
        ///b)Sunil Gavaskar                        
        ///c)KapilDev	               
        ///d)Brain Lara.
        /// </summary>
        internal static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which of the following trophies is 
        ///NOT associated with cricket?
        ///a)Thomas Cup	                                                                        b)RohintonBaria Trophy                                               
        ///c)Duleep Trophy	                                                          
        ///d)Charminar Challenge cup.
        /// </summary>
        internal static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Cannon, Cue and Pot&apos; are three terms 
        ///associated with?
        ///a)Golf Only	                                                            
        ///b)Billiards only                          
        ///c)Billiards, Golf and shooting	                                            
        ///d)Both Billiards  and golf.
        /// </summary>
        internal static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Headquarters of the International 
        ///Olympic Committee is in?
        ///a)Italy	                           
        ///b)Switzerland                               
        ///c)Belgium	                                             
        ///d)France.
        /// </summary>
        internal static string q6 {
            get {
                return ResourceManager.GetString("q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name the International Tennis Player 
        ///who has won 8 men singles titles of 
        ///French Open Tennis Tournament?
        ///a)Andy Murray                
        ///b)Novak Djokovic                       
        ///c)Rafael Nadal                                     
        ///d)Roger Fedrer.
        /// </summary>
        internal static string q7 {
            get {
                return ResourceManager.GetString("q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which player is known as Prince of 
        ///Port of Spain?
        ///a)Chris Gayle                    
        ///b)Vivian Richards                       
        ///c)Courtney Ambrose                          
        ///d)Brian Lara.
        /// </summary>
        internal static string q8 {
            get {
                return ResourceManager.GetString("q8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is the maximum number of 
        ///clubs a golfer is allowed in his or her
        /// bag in a round of Golf?
        ///a)10                                    
        ///b)12                                              
        ///c)14                                                        
        ///d)16.
        /// </summary>
        internal static string q9 {
            get {
                return ResourceManager.GetString("q9", resourceCulture);
            }
        }
    }
}
