//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiseOfUltron_29Feb2016.Resources.Question {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Rules1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Rules1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiseOfUltron_29Feb2016.Resources.Question.Rules1", typeof(Rules1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world is witnessing an outrageous situation of cold war; 
        ///countries secretly trying to wage cyber wars against each other. In 
        ///order to stop this, the UN’s artificial intelligence unit has installed
        ///an AI on the Internet. Upon activation, Ultron immediately perceived 
        ///the human race as a “security threat”, and formulated a plan to 
        ///systematically take control over humanity. Hence initiating 
        ///unprecedented cyber-attacks by deploying viruses over the internet.
        ///Governments’ confidential documents, s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As you have seen, that ultron is
        ///way more stronger than you think. The
        ///pace at which it is hacking in every 
        ///system round the globe is alarmig and
        ///only few hacker dens around the world
        ///are left safe. Yu are the last hope for
        ///whole mankind and have the
        ///responsibility for saving us from this
        ///disastrous AI.
        ///Our valuable data is within the system
        ///and if Ultron is able to get that data
        ///then it can control all our drones and
        ///robots. The fate of humanity lies in
        ///your hand now. We dont have much 
        ///time [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NickReply {
            get {
                return ResourceManager.GetString("NickReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello Coder, Welcome to Hacker Den,
        ///Ghaziabad. As we all know that we have 
        ///developed an AI &apos;The Ultron&apos; to fight
        ///alien attacks on our online world after
        ///the New York incident. But unfortunately
        ///that AI has sensed humans itself as the
        ///greatest threat to humanity and is now
        ///working to clean off humanity.
        ///of earth&apos;s face..
        /// </summary>
        internal static string NickSpeaks {
            get {
                return ResourceManager.GetString("NickSpeaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. There are three rounds. There will be a time limit of 20 
        ///    minutes for round 1 and round 2.
        ///2. Round 1 and 2 consists of 5 Questions. 4 Questions will 
        ///    be output based and you will be writing a piece of code
        ///    for 5th Question.
        ///3. It is important for the participants to save the code file 
        ///    with teamId_roundNo.c .
        ///4. The correct answer to first 4 Questions will generate a 
        ///    key that will act as input to the fifth question.
        ///5. Round 3 will be a rapid fire round that will have a 
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RulesStart {
            get {
                return ResourceManager.GetString("RulesStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HaHaHaHa . . . . .
        ///You amateurs think that you can
        ///stop me. . . It&apos;s because of you humans
        ///that this planet is suffering. But no 
        ///worries to that because I am gonna kill 
        ///each one of you and will save this planet. 
        ///You people are weak and this planet is 
        ///not  gonna  suffer  further  for  your 
        ///weakness. All your actions to stop me 
        ///will be in vain.  Now there is no 
        ///stopping me because . . . 
        ///
        ///There are no strings on me..
        /// </summary>
        internal static string UltronSpeaks {
            get {
                return ResourceManager.GetString("UltronSpeaks", resourceCulture);
            }
        }
    }
}
